name: Continuous Integration
on:
  push:
    branches:
      - '**'
jobs:
  build:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: adopt
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Set Gradlew executable
        run: chmod +x ./gradlew
      - name: Gradle build
        run: ./gradlew build
